name: Build, push image to GCR and Deploy in Cloudrun

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      TAG: "1.0.${{ github.run_number }}"
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Building Docker image
      run: |
        cd //home/runner/work/github-gowtham/github-gowtham/Skipify/src/deidentify/
        docker build -t cloudrun_image .

    #- name: Determine image tag
    #  id: tag
    #  run: echo ::set-env name=IMAGE_TAG::v${{ github.run_number }}


    # Authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.CLOUDRUN_GCP }}'

    - name: Push image to GCR
      run: |
        docker tag cloudrun_image gcr.io/${{ secrets.PROJECT_ID }}/cloudrun_image:${{ env.TAG }}
        gcloud auth configure-docker
        docker push gcr.io/${{ secrets.PROJECT_ID }}/cloudrun_image:${{ env.TAG }}

    - name: Set Docker image tag
      id: set-tag
      run: |
        sed -i 's/^image = ".*"$/image = "gcr.io\/skipify-demo\/cloudrun_image:${{ env.TAG }}"/' /home/runner/work/github-gowtham/github-gowtham/Skipify/tf/cloudrun/deidentify/terraform.tfvars
        #echo 'image = "gcr.io/skipify-demo/cloudrun_image:${{ env.TAG }}"' > /home/runner/work/github-gowtham/github-gowtham/Skipify/tf/cloudrun/deidentify/terraform.tfvars
        #echo "image = \"gcr.io/skipify-demo/cloudrun_image:${{ env.TAG }}\"" > /home/runner/work/github-gowtham/github-gowtham/Skipify/tf/cloudrun/deidentify/terraform.tfvars
        #echo 'image = "gcr.io/skipify-demo/cloudrun_image:${{ env.TAG }}"' > /home/runner/work/github-gowtham/github-gowtham/Skipify/tf/cloudrun/deidentify/terraform.tfvars
        cat /home/runner/work/github-gowtham/github-gowtham/Skipify/tf/cloudrun/deidentify/terraform.tfvars

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: |
        pwd
        cd /home/runner/work/github-gowtham/github-gowtham/Skipify/tf/cloudrun/deidentify
        ls
        terraform init

    - name: Terraform Plan
      run: |
        cd /home/runner/work/github-gowtham/github-gowtham/Skipify/tf/cloudrun/deidentify
        ls
        terraform plan

    - name: Terraform Apply
      run: |
        cd /home/runner/work/github-gowtham/github-gowtham/Skipify/tf/cloudrun/deidentify
        terraform apply -auto-approve
